local M = {}

M.DiagnosticsOutlined = {
  Error = " ",
  Hint = " ",
  Info = " ",
  Warn = " ",
}

M.Diagnostics = {
  Error = " ",
  Warn = " ",
  Hint = " ",
  Info = " ",
}

M.Folder = {
  FoldOpened = "",
  FoldClosed = "",
  Default = "",
  Opened = "",
  Empty = "",
  EmptyOpened = "",
  Symlink = "",
  SymlinkOpened = "",
}

M.Git = {
  Branch = "",
  Gitlab = "",
  Github = "󰊤",
  Copilot = "",
  Added = "",
  AddedFilled = "",
  Staged = "",
  StagedFilled = "",
  Unstaged = "󰅘",
  UnstagedFilled = "󰅗",
  Modified = "",
  Unmerged = "",
  Renamed = "",
  Deleted = "",
  DeletedFilled = "",
  Untracked = "",
  Ignored = "",
  Conflict = "",
}

M.KindIcons = {
  Array = " ",
  Boolean = " ",
  Class = " ",
  Color = " ",
  Constant = " ",
  Constructor = " ",
  Copilot = " ",
  Enum = " ",
  EnumMember = " ",
  Event = " ",
  Field = " ",
  File = " ",
  Folder = " ",
  Function = " ",
  Interface = " ",
  Key = " ",
  Keyword = " ",
  Method = " ",
  Module = " ",
  Namespace = " ",
  Null = " ",
  Number = " ",
  Object = " ",
  Operator = " ",
  Package = " ",
  Property = " ",
  Reference = " ",
  Snippet = " ",
  String = " ",
  Struct = " ",
  Text = " ",
  TypeParameter = " ",
  Unit = " ",
  Value = " ",
  Variable = " ",
}

M.SpinnerFrames = {
  "⠋ ",
  "⠙ ",
  "⠹ ",
  "⠸ ",
  "⠼ ",
  "⠴ ",
  "⠦ ",
  "⠧ ",
  "⠇ ",
  "⠏ ",
}

M.Common = {
  ArrowLeft = "",
  ArrowRight = "",
  Circle = " ",
  CircleOutlined = " ",
  CircleHalfLeft = "",
  CircleHalfRight = "",
  ChevronLeft = "",
  ChevronRight = "",
  Telescope = "",
  Lightbulb = "",
  Bookmark = "",
  Calendar = "",
  Squirrel = " ",
  Horse = "♞",
  Block = "▊",
  Table = "",
  Evil = "",
  Vim = " ",
  Cmd = " ",
  CmdOutlined = " ",
  Flash = "",
  File = " ",
  FileRefresh = "󰤘 ",
  Note = "󱙓 ",
  Cog = " ",
  Import = " ",
  Keys = " ",
  Lazy = "󰒲 ",
  Bullet = "●",
  BulletOutlined = "○",
  Package = " ",
  runtime = " ",
  Source = " ",
  Start = "",
  Check = "✔ ",
  Star = "★",
  Slash = "╱",
  Lens = "◍ ",
  Close = "󰅗 ",
  Reverse = " ",
  RootFolderOpened = " ",
  String = " ",
  RecentFiles = " ",
  ColorMode = " ",
  ColorPalette = " ",
  Word = "󱀽 ",
  Continue = " ",
  Question = "󰋖",
  EyeOpen = "󰈈 ",
  Keyboard = "󰌌 ",
  Marker = "󰙒 ",
}

return M
